#
# Copyright 2021 New Relic Corporation. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
version: '3.7'
services:
# The Database
  mysqldb:
    image: mysql/mysql-server:8.0.28
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: database
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_HOST: mysqldb
    ports:
      - "33061:3306"
    container_name: mysqldb

  redisdb:
    build:
      context: .
      dockerfile: files/Dockerfile.redis
    restart: always
    ports:
      - "6379:6379"
    container_name: redisdb

  memcached:
    image: memcached:latest
    restart: always
    ports:
      - "11211:11211"
    container_name: memcached

  postgres:
    image: postgres:9-alpine
    restart: always
    environment:
       POSTGRES_PASSWORD: root
       POSTGRES_USER: postgres
       POSTGRES_DB: db
       PGDATA: /tmp
    ports:
      - "5432:5432"
    container_name: postgres

  agent:
    build:
      context: .
      dockerfile: files/Dockerfile
      args:
        - PHP_VER=${PHP_VER}
    user: ${UID}:${GID}
    environment:
      MYSQL_DB: database
      MYSQL_USER: root
      MYSQL_PASSWD: admin
      MYSQL_HOST: mysqldb
      REDIS_HOST: redisdb
      REDIS_HOST: redisdb
      MEMCACHE_HOST: memcached
      PG_HOST: postgres
      PG_PORT: 5432
      PREDIS_HOME: /usr/src/myapp/vendor/predis/predis/
      PS1: "New Relic > "
      NEWRELIC_COLLECTOR_HOST : ${NEWRELIC_COLLECTOR_HOST:-collector.newrelic.com}
      NEWRELIC_LICENSE_KEY: ${NEWRELIC_LICENSE_KEY}
    volumes:
       - ${PWD}:/usr/src/myapp
    working_dir: /usr/src/myapp
    stdin_open: true
    tty: true
    container_name: agent
